name: surveilpro
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  image: ^4.5.4
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  video_player: ^2.9.5
  shared_preferences: ^2.5.3
  http: ^1.3.0
  provider: ^6.1.4
  tflite_flutter: ^0.11.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/placeholderimage.jpg

